//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public string PassengerNameRecord { get; set; }
        public int SeatNumber { get; set; }
        public string CoachNumber { get; set; }
        public string PassengerName { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public int TrainId { get; set; }
        public string BookedBy { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
