//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int TrainId { get; set; }
        public string AvailableDate { get; set; }
        public string EmailId { get; set; }
        public string PassengerNameRecord { get; set; }
        public string ReservationDate { get; set; }
        public string ReservationStatus { get; set; }
    
        public virtual Train Train { get; set; }
        public virtual User User { get; set; }
    }
}
