//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int TrainId { get; set; }
        public int StopNumber { get; set; }
        public string StationId { get; set; }
        public string ArrivalTime { get; set; }
        public string DepartureTime { get; set; }
        public int SourceDistance { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
