//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainStatu
    {
        public int TrainId { get; set; }
        public string AvailableDate { get; set; }
        public Nullable<int> BookedSeats1 { get; set; }
        public Nullable<int> BookedSeats2 { get; set; }
        public Nullable<int> BookedSeats3 { get; set; }
        public Nullable<int> BookedSeats4 { get; set; }
        public Nullable<int> WaitingSeats1 { get; set; }
        public Nullable<int> WaitingSeats2 { get; set; }
        public Nullable<int> WaitingSeats3 { get; set; }
        public Nullable<int> WaitingSeats4 { get; set; }
        public Nullable<int> AvailableSeats1 { get; set; }
        public Nullable<int> AvailableSeats2 { get; set; }
        public Nullable<int> AvailableSeats3 { get; set; }
        public Nullable<int> AvailableSeats4 { get; set; }
    }
}
