//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainClass
    {
        public int TrainId { get; set; }
        public int FareClass1 { get; set; }
        public int FareClass2 { get; set; }
        public int FareClass3 { get; set; }
        public int SeatClass1 { get; set; }
        public int SeatClass2 { get; set; }
        public int SeatClass3 { get; set; }
    }
}
